# Generated by Django 4.2.15 on 2024-09-22 10:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_post_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.PROTECT, to='blog.category'),
        ),
    ]
