# Generated by Django 4.2.15 on 2024-09-23 22:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_rename_user_comment_author'),
    ]

    operations = [
        migrations.RenameField(
            model_name='like',
            old_name='user',
            new_name='author',
        ),
        migrations.RenameField(
            model_name='share',
            old_name='user',
            new_name='author',
        ),
    ]
