# Generated by Django 4.2.15 on 2024-09-24 06:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_rename_user_like_author_rename_user_share_author'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Share',
        ),
    ]
